#!/bin/bash

# macOS
if [[ $OSTYPE == 'darwin'* ]]; then
  # to push to hub.docker.com
  security -v unlock-keychain ~/Library/Keychains/login.keychain-db
fi

# Build multi-arch container
docker buildx build --push -f fastapi/Dockerfile --platform linux/amd64,linux/arm64 --tag sage3/fastapi:latest .


